##Spring Configuration
server:
  port: 8080
spring:
  application:
    name: tallergrupo7
  devtools:
    add-properties: false
  profiles:
    include:

balances:
  url: https://autumn-grass-4374.getsandbox.com/v1/operations/product-specific/deposits/accounts/balances
  timeout: 5
movements:
  url: https://white-glade-742.getsandbox.com/deposit/movements
  timeout: 5
